### ISSUE TITLE
Youtube Validator Issue

### ISSUE THREAD

**Issue by PhuocOng** [LoopTube2004/looptube#22]
The validateYouTubeLink function in YoutubeValidator.js don't work for input url like: "123", "123431asv",...Youtube Validator Issue #7

**Comment by PhuocOng** [comment]
Need to import the youtubevalidator.js function into fetchyoutubedata

**Comment by phuc-nguyen-tran** [comment]
@PhuocOng still show error when deleting the form. The "split" error when extracting youtube id

**Comment by PhuocOng** [comment]
Still have bug when we try to modify url after submitting successfully. Reason come from <Iframe> receive directly living state value. 
Solution: => Create 4 more value wait for valid state value, and only passed to <Iframe> after submitting
